/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.MeuPrimeiroProjeto;

public class App {


    public static void main(String[] args) {
        System.out.println("Hello World");
        System.out.println("Meu segundo comando de saida");
    }
}
